# Generated by Django 2.2 on 2023-04-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
